server:
  port: 8080
  host: localhost
  timeout: 30s

database:
  host: localhost
  port: 5432
  name: student_db
  user: postgres
  password: postgres
  sslmode: disable
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 1h

logging:
  level: info
  format: json

tracing:
  enabled: true
  service_name: student-service
  endpoint: http://localhost:14268/api/traces